# CMake generated Testfile for 
# Source directory: /home/SVF-tools/Software-Analysis-Studio/Assignment-3
# Build directory: /home/SVF-tools/Software-Analysis-Studio/Assignment-3
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[ass3-pta-cpp/Tests/testcases/pta/test1.ll]=] "/home/SVF-tools/Software-Analysis-Studio/bin/ass3" "-pta" "/home/SVF-tools/Software-Analysis-Studio/Assignment-3/Tests/testcases/pta/test1.ll")
set_tests_properties([=[ass3-pta-cpp/Tests/testcases/pta/test1.ll]=] PROPERTIES  TIMEOUT "5" WORKING_DIRECTORY "/home/SVF-tools/Software-Analysis-Studio/bin" _BACKTRACE_TRIPLES "/home/SVF-tools/Software-Analysis-Studio/Assignment-3/CMakeLists.txt;24;add_test;/home/SVF-tools/Software-Analysis-Studio/Assignment-3/CMakeLists.txt;0;")
add_test([=[ass3-pta-cpp/Tests/testcases/pta/test2.ll]=] "/home/SVF-tools/Software-Analysis-Studio/bin/ass3" "-pta" "/home/SVF-tools/Software-Analysis-Studio/Assignment-3/Tests/testcases/pta/test2.ll")
set_tests_properties([=[ass3-pta-cpp/Tests/testcases/pta/test2.ll]=] PROPERTIES  TIMEOUT "5" WORKING_DIRECTORY "/home/SVF-tools/Software-Analysis-Studio/bin" _BACKTRACE_TRIPLES "/home/SVF-tools/Software-Analysis-Studio/Assignment-3/CMakeLists.txt;24;add_test;/home/SVF-tools/Software-Analysis-Studio/Assignment-3/CMakeLists.txt;0;")
add_test([=[ass3-pta-cpp/Tests/testcases/pta/test3.ll]=] "/home/SVF-tools/Software-Analysis-Studio/bin/ass3" "-pta" "/home/SVF-tools/Software-Analysis-Studio/Assignment-3/Tests/testcases/pta/test3.ll")
set_tests_properties([=[ass3-pta-cpp/Tests/testcases/pta/test3.ll]=] PROPERTIES  TIMEOUT "5" WORKING_DIRECTORY "/home/SVF-tools/Software-Analysis-Studio/bin" _BACKTRACE_TRIPLES "/home/SVF-tools/Software-Analysis-Studio/Assignment-3/CMakeLists.txt;24;add_test;/home/SVF-tools/Software-Analysis-Studio/Assignment-3/CMakeLists.txt;0;")
add_test([=[ass3-icfg-cpp/Tests/testcases/icfg/test1.ll]=] "/home/SVF-tools/Software-Analysis-Studio/bin/ass3" "-icfg" "/home/SVF-tools/Software-Analysis-Studio/Assignment-3/Tests/testcases/icfg/test1.ll")
set_tests_properties([=[ass3-icfg-cpp/Tests/testcases/icfg/test1.ll]=] PROPERTIES  TIMEOUT "5" WORKING_DIRECTORY "/home/SVF-tools/Software-Analysis-Studio/bin" _BACKTRACE_TRIPLES "/home/SVF-tools/Software-Analysis-Studio/Assignment-3/CMakeLists.txt;35;add_test;/home/SVF-tools/Software-Analysis-Studio/Assignment-3/CMakeLists.txt;0;")
add_test([=[ass3-icfg-cpp/Tests/testcases/icfg/test2.ll]=] "/home/SVF-tools/Software-Analysis-Studio/bin/ass3" "-icfg" "/home/SVF-tools/Software-Analysis-Studio/Assignment-3/Tests/testcases/icfg/test2.ll")
set_tests_properties([=[ass3-icfg-cpp/Tests/testcases/icfg/test2.ll]=] PROPERTIES  TIMEOUT "5" WORKING_DIRECTORY "/home/SVF-tools/Software-Analysis-Studio/bin" _BACKTRACE_TRIPLES "/home/SVF-tools/Software-Analysis-Studio/Assignment-3/CMakeLists.txt;35;add_test;/home/SVF-tools/Software-Analysis-Studio/Assignment-3/CMakeLists.txt;0;")
add_test([=[ass3-icfg-cpp/Tests/testcases/icfg/test3.ll]=] "/home/SVF-tools/Software-Analysis-Studio/bin/ass3" "-icfg" "/home/SVF-tools/Software-Analysis-Studio/Assignment-3/Tests/testcases/icfg/test3.ll")
set_tests_properties([=[ass3-icfg-cpp/Tests/testcases/icfg/test3.ll]=] PROPERTIES  TIMEOUT "5" WORKING_DIRECTORY "/home/SVF-tools/Software-Analysis-Studio/bin" _BACKTRACE_TRIPLES "/home/SVF-tools/Software-Analysis-Studio/Assignment-3/CMakeLists.txt;35;add_test;/home/SVF-tools/Software-Analysis-Studio/Assignment-3/CMakeLists.txt;0;")
add_test([=[ass3-taint-cpp/Tests/testcases/taint/test1.ll]=] "/home/SVF-tools/Software-Analysis-Studio/bin/ass3" "-taint" "/home/SVF-tools/Software-Analysis-Studio/Assignment-3/Tests/testcases/taint/test1.ll")
set_tests_properties([=[ass3-taint-cpp/Tests/testcases/taint/test1.ll]=] PROPERTIES  TIMEOUT "5" WORKING_DIRECTORY "/home/SVF-tools/Software-Analysis-Studio/bin" _BACKTRACE_TRIPLES "/home/SVF-tools/Software-Analysis-Studio/Assignment-3/CMakeLists.txt;46;add_test;/home/SVF-tools/Software-Analysis-Studio/Assignment-3/CMakeLists.txt;0;")
add_test([=[ass3-taint-cpp/Tests/testcases/taint/test2.ll]=] "/home/SVF-tools/Software-Analysis-Studio/bin/ass3" "-taint" "/home/SVF-tools/Software-Analysis-Studio/Assignment-3/Tests/testcases/taint/test2.ll")
set_tests_properties([=[ass3-taint-cpp/Tests/testcases/taint/test2.ll]=] PROPERTIES  TIMEOUT "5" WORKING_DIRECTORY "/home/SVF-tools/Software-Analysis-Studio/bin" _BACKTRACE_TRIPLES "/home/SVF-tools/Software-Analysis-Studio/Assignment-3/CMakeLists.txt;46;add_test;/home/SVF-tools/Software-Analysis-Studio/Assignment-3/CMakeLists.txt;0;")
add_test([=[ass3-taint-cpp/Tests/testcases/taint/test3.ll]=] "/home/SVF-tools/Software-Analysis-Studio/bin/ass3" "-taint" "/home/SVF-tools/Software-Analysis-Studio/Assignment-3/Tests/testcases/taint/test3.ll")
set_tests_properties([=[ass3-taint-cpp/Tests/testcases/taint/test3.ll]=] PROPERTIES  TIMEOUT "5" WORKING_DIRECTORY "/home/SVF-tools/Software-Analysis-Studio/bin" _BACKTRACE_TRIPLES "/home/SVF-tools/Software-Analysis-Studio/Assignment-3/CMakeLists.txt;46;add_test;/home/SVF-tools/Software-Analysis-Studio/Assignment-3/CMakeLists.txt;0;")
